version = 0.1

[default.deploy.parameters]
stack_name = "tweeter-server"
s3_bucket = "tweeter.dbl00m11.click"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []